### ISSUE TITLE
https://gocon.jp/として公開する

### ISSUE THREAD

**Issue by vzvu3k6k** [GoCon/gocon.github.io#1]
- [x] GitHub Pagesの設定画面でカスタムドメインとしてgocon.jpを指定する
    - 手順は[GitHubのドキュメント](https://docs.github.com/ja/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)を参照してください。
- [x] gocon.jpのDNS設定を更新する
    - :warning: [ページの乗っ取りを防ぐため](https://docs.github.com/ja/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#about-custom-domain-configuration)、GitHub Pagesのカスタムドメインの設定を行ったあとで実施してください。
    - 設定内容は同じく[GitHubのドキュメント](https://docs.github.com/ja/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)を参照してください。
- 完了！

**Comment by tenntenn** [comment]
@vzvu3k6k 
完了しました！
